language: java
sudo: false
addons:
  sonarcloud:
    organization: wojciechzankowski-github
jdk:
  - openjdk11
script:
  - set -e
  - if [ $TRAVIS_BRANCH == 'master' ];
    then
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -P javadoc;
    else
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar;
    fi
  # Workaround for pit aggregated reports https://github.com/hcoles/pitest/issues/621
  - if [ $TRAVIS_BRANCH == 'master' ];
    then
      mvn install -DskipTests=true -P mutation;
    fi
after_success:
  - bash ./scripts/deploy.sh
  - bash <(curl -s https://codecov.io/bash)
