# This workflow will build Javadoc and pitest reports

name: Documentation workflow

on:
  push

jobs:
  documentation:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            java: [ 11 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Javadoc generation
      run: mvn package -DskipTests=true -P javadoc --file pom.xml
    - name: Deploy documentation
      run: sudo /scripts/deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

